// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: cpu.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cpu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User   float32 `protobuf:"fixed32,1,opt,name=user,proto3" json:"user,omitempty"`
	System float32 `protobuf:"fixed32,2,opt,name=system,proto3" json:"system,omitempty"`
	Idle   float32 `protobuf:"fixed32,3,opt,name=idle,proto3" json:"idle,omitempty"`
}

func (x *Cpu) Reset() {
	*x = Cpu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cpu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cpu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cpu) ProtoMessage() {}

func (x *Cpu) ProtoReflect() protoreflect.Message {
	mi := &file_cpu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cpu.ProtoReflect.Descriptor instead.
func (*Cpu) Descriptor() ([]byte, []int) {
	return file_cpu_proto_rawDescGZIP(), []int{0}
}

func (x *Cpu) GetUser() float32 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *Cpu) GetSystem() float32 {
	if x != nil {
		return x.System
	}
	return 0
}

func (x *Cpu) GetIdle() float32 {
	if x != nil {
		return x.Idle
	}
	return 0
}

var File_cpu_proto protoreflect.FileDescriptor

var file_cpu_proto_rawDesc = []byte{
	0x0a, 0x09, 0x63, 0x70, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69,
	0x22, 0x45, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x73, 0x74, 0x75,
	0x62, 0x2f, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cpu_proto_rawDescOnce sync.Once
	file_cpu_proto_rawDescData = file_cpu_proto_rawDesc
)

func file_cpu_proto_rawDescGZIP() []byte {
	file_cpu_proto_rawDescOnce.Do(func() {
		file_cpu_proto_rawDescData = protoimpl.X.CompressGZIP(file_cpu_proto_rawDescData)
	})
	return file_cpu_proto_rawDescData
}

var file_cpu_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cpu_proto_goTypes = []interface{}{
	(*Cpu)(nil), // 0: api.cpu
}
var file_cpu_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cpu_proto_init() }
func file_cpu_proto_init() {
	if File_cpu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cpu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cpu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cpu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cpu_proto_goTypes,
		DependencyIndexes: file_cpu_proto_depIdxs,
		MessageInfos:      file_cpu_proto_msgTypes,
	}.Build()
	File_cpu_proto = out.File
	file_cpu_proto_rawDesc = nil
	file_cpu_proto_goTypes = nil
	file_cpu_proto_depIdxs = nil
}
