// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: stats.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type STATS int32

const (
	STATS_NOTHING     STATS = 0
	STATS_ALL         STATS = 1
	STATS_CPU         STATS = 2
	STATS_LOADAVERAGE STATS = 4
	STATS_LOADDISK    STATS = 8
)

// Enum value maps for STATS.
var (
	STATS_name = map[int32]string{
		0: "NOTHING",
		1: "ALL",
		2: "CPU",
		4: "LOADAVERAGE",
		8: "LOADDISK",
	}
	STATS_value = map[string]int32{
		"NOTHING":     0,
		"ALL":         1,
		"CPU":         2,
		"LOADAVERAGE": 4,
		"LOADDISK":    8,
	}
)

func (x STATS) Enum() *STATS {
	p := new(STATS)
	*p = x
	return p
}

func (x STATS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (STATS) Descriptor() protoreflect.EnumDescriptor {
	return file_stats_proto_enumTypes[0].Descriptor()
}

func (STATS) Type() protoreflect.EnumType {
	return &file_stats_proto_enumTypes[0]
}

func (x STATS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use STATS.Descriptor instead.
func (STATS) EnumDescriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{0}
}

type Responce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CPU     *Cpu         `protobuf:"bytes,1,opt,name=CPU,proto3" json:"CPU,omitempty"`
	LoadAvg *Loadaverage `protobuf:"bytes,2,opt,name=LoadAvg,proto3" json:"LoadAvg,omitempty"`
	Disks   []*Loaddisk  `protobuf:"bytes,3,rep,name=Disks,proto3" json:"Disks,omitempty"`
}

func (x *Responce) Reset() {
	*x = Responce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Responce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Responce) ProtoMessage() {}

func (x *Responce) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Responce.ProtoReflect.Descriptor instead.
func (*Responce) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{0}
}

func (x *Responce) GetCPU() *Cpu {
	if x != nil {
		return x.CPU
	}
	return nil
}

func (x *Responce) GetLoadAvg() *Loadaverage {
	if x != nil {
		return x.LoadAvg
	}
	return nil
}

func (x *Responce) GetDisks() []*Loaddisk {
	if x != nil {
		return x.Disks
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N       int32 `protobuf:"varint,1,opt,name=N,proto3" json:"N,omitempty"`
	M       int32 `protobuf:"varint,2,opt,name=M,proto3" json:"M,omitempty"`
	Bitmask STATS `protobuf:"varint,3,opt,name=bitmask,proto3,enum=api.STATS" json:"bitmask,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *Request) GetM() int32 {
	if x != nil {
		return x.M
	}
	return 0
}

func (x *Request) GetBitmask() STATS {
	if x != nil {
		return x.Bitmask
	}
	return STATS_NOTHING
}

var File_stats_proto protoreflect.FileDescriptor

var file_stats_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61,
	0x70, 0x69, 0x1a, 0x09, 0x63, 0x70, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x6c,
	0x6f, 0x61, 0x64, 0x2d, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0f, 0x6c, 0x6f, 0x61, 0x64, 0x2d, 0x64, 0x69, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x77, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1a,
	0x0a, 0x03, 0x43, 0x50, 0x55, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x70, 0x75, 0x52, 0x03, 0x43, 0x50, 0x55, 0x12, 0x2a, 0x0a, 0x07, 0x4c, 0x6f,
	0x61, 0x64, 0x41, 0x76, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6c, 0x6f, 0x61, 0x64, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x07, 0x4c,
	0x6f, 0x61, 0x64, 0x41, 0x76, 0x67, 0x12, 0x23, 0x0a, 0x05, 0x44, 0x69, 0x73, 0x6b, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6f, 0x61, 0x64,
	0x64, 0x69, 0x73, 0x6b, 0x52, 0x05, 0x44, 0x69, 0x73, 0x6b, 0x73, 0x22, 0x4b, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x01, 0x4e, 0x12, 0x0c, 0x0a, 0x01, 0x4d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x4d, 0x12, 0x24, 0x0a, 0x07, 0x62, 0x69, 0x74, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x54, 0x41, 0x54, 0x53, 0x52,
	0x07, 0x62, 0x69, 0x74, 0x6d, 0x61, 0x73, 0x6b, 0x2a, 0x45, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x54,
	0x53, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x4f, 0x54, 0x48, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x07,
	0x0a, 0x03, 0x41, 0x4c, 0x4c, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x50, 0x55, 0x10, 0x02,
	0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x4f, 0x41, 0x44, 0x41, 0x56, 0x45, 0x52, 0x41, 0x47, 0x45, 0x10,
	0x04, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x4f, 0x41, 0x44, 0x44, 0x49, 0x53, 0x4b, 0x10, 0x08, 0x32,
	0x32, 0x0a, 0x03, 0x53, 0x53, 0x44, 0x12, 0x2b, 0x0a, 0x08, 0x53, 0x75, 0x62, 0x73, 0x72, 0x69,
	0x62, 0x65, 0x12, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x73, 0x74, 0x75, 0x62, 0x2f, 0x3b, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stats_proto_rawDescOnce sync.Once
	file_stats_proto_rawDescData = file_stats_proto_rawDesc
)

func file_stats_proto_rawDescGZIP() []byte {
	file_stats_proto_rawDescOnce.Do(func() {
		file_stats_proto_rawDescData = protoimpl.X.CompressGZIP(file_stats_proto_rawDescData)
	})
	return file_stats_proto_rawDescData
}

var file_stats_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stats_proto_goTypes = []interface{}{
	(STATS)(0),          // 0: api.STATS
	(*Responce)(nil),    // 1: api.Responce
	(*Request)(nil),     // 2: api.Request
	(*Cpu)(nil),         // 3: api.cpu
	(*Loadaverage)(nil), // 4: api.loadaverage
	(*Loaddisk)(nil),    // 5: api.loaddisk
}
var file_stats_proto_depIdxs = []int32{
	3, // 0: api.Responce.CPU:type_name -> api.cpu
	4, // 1: api.Responce.LoadAvg:type_name -> api.loadaverage
	5, // 2: api.Responce.Disks:type_name -> api.loaddisk
	0, // 3: api.Request.bitmask:type_name -> api.STATS
	2, // 4: api.SSD.Subsribe:input_type -> api.Request
	1, // 5: api.SSD.Subsribe:output_type -> api.Responce
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_stats_proto_init() }
func file_stats_proto_init() {
	if File_stats_proto != nil {
		return
	}
	file_cpu_proto_init()
	file_load_average_proto_init()
	file_load_disk_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_stats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Responce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stats_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_proto_goTypes,
		DependencyIndexes: file_stats_proto_depIdxs,
		EnumInfos:         file_stats_proto_enumTypes,
		MessageInfos:      file_stats_proto_msgTypes,
	}.Build()
	File_stats_proto = out.File
	file_stats_proto_rawDesc = nil
	file_stats_proto_goTypes = nil
	file_stats_proto_depIdxs = nil
}
