name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Build project
        run: make build-in-docker

      - name: Create env variables
        run: |
          echo "VERSION=$(scripts/version.sh)" >> $GITHUB_ENV

      - name: Test evn variables
        run: echo $VERSION

#      - name: "✏️ Generate release changelog"
#        uses: heinrichreimer/github-changelog-generator-action@v2.3
#        with:
#          token: $
#          output:

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
#          body_path: build/$VERSION-CHANGELOG.md
          files: build/ssd-app-*.tar.gz
        env:
#          GITHUB_TOKEN: $
